name: ci

on:
  pull_request:
  push:
    branches: [main]
    paths: ['**/package.json', pnpm-lock.yaml]

jobs:
  lint-monorepo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Lint monorepo
        run: pnpm sherif -r multiple-dependency-versions

      - name: Check engine ranges, peer dependency ranges and installed versions
        run: pnpm installed-check --no-include-workspace-root --ignore-dev
